### ISSUE TITLE
May I ask one concern about whether mac with M2/M1 could install it?

### ISSUE THREAD

**Issue by quzhixue-Kimi** [dockur/windows-arm#42]
Hi there,

It is so nice to find your repo and star has been marked.
One concern is that "is it possible to install docker-windows arm in macbook with M2?"

Both the OrbStack and Podman have been installed as the docker engine.

Looking forward to your feedback.

BR
Kimi

**Comment by vlorian-de** [comment]
May I ask why you dont try it by yourself?

**Comment by pramodhrachuri** [comment]
@quzhixue-Kimi were you able to do it?

**Comment by quzhixue-Kimi** [comment]
hi @pramodhrachuri , 

As vlorian-de said, I have tried, but failed to startup.

BR
Kimi
